server: 
  port: ${PORT:${SERVER_PORT}}
spring:
    data:
        mongodb:
            uri: mongodb+srv://jespinoza:jest444@jespinoza.is5j4.mongodb.net/card_data        
logging:
 file: 
   name: log/CardService.log     
 pattern:
   console: "%d [%thread] %-5level %-60logger{40} : %msg%n"
 logback:
    rollingpolicy:
      max-file-size: 1MB   
      file-name-pattern: log/CardService.%d{yyyy-MM-dd}.%i.log
      total-size-cap: 11MB
      max-history: 10
      clean-history-on-start: true   
eureka: 
  client: 
    service-url: 
      defaultZone: http://localhost:8091/eureka/
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
management:
    endpoints:
        web:
          exposure:
             include: "*"