server: 
  port: 8081
eureka: 
  client: 
    service-url: 
      defaultZone: http://localhost:8091/banking_discovery
spring:
    data:
        mongodb:
            uri: mongodb+srv://jespinoza.is5j4.mongodb.net
            database: ${mongo_database}
            username: ${mongo_user}
            password: ${mongo_password}