server: 
  port: 8083
eureka: 
  client: 
    service-url: 
      defaultZone: http://localhost:8091/eureka/
      
spring:
  data:
    mongodb:
      uri: mongodb+srv://jespinoza:jest444@jespinoza.is5j4.mongodb.net/account_data
      
logging:
 file: 
   name: log/AccountService.log     
 pattern:
   console: "%d [%thread] %-5level %-60logger{40} : %msg%n"
 logback:
    rollingpolicy:
      max-file-size: 1MB   
      file-name-pattern: log/AccountService.%d{yyyy-MM-dd}.%i.log
      total-size-cap: 11MB
      max-history: 10
      clean-history-on-start: true
      
management:
    endpoints:
        web:
          exposure:
             include: "*"