server: 
  port: 8087
eureka: 
  client: 
    service-url: 
      defaultZone: http://localhost:8091/eureka/
      
spring:
  data:
    mongodb:
      uri: mongodb+srv://jespinoza:jest444@jespinoza.is5j4.mongodb.net/witdrawal_data
      
logging:
  file:
    name: log/WitdrawalService.log
  pattern:
    console: "%d [%thread] %-5level %-60logger{40} : %msg%n"
  logback:
    rollingpolicy:
      max-file-size: 1MB
      file-name-pattern: log/WitdrawalService-%d{yyyy-MM-dd}.%i.log
      total-size-cap: 11MB
      clean-history-on-start: true
      max-history: 10
      
management:
    endpoints:
        web:
          exposure:
             include: "*"