server: 
  port: 8080
eureka: 
  client: 
    service-url: 
      defaultZone: http://localhost:8091/eureka/
spring:
    cloud:
        gateway:
            discovery:
                locator:
                    enabled: true
            routes:
              - id: banking-customer-service
                uri: http://localhost:8082/customer
                predicates:
                  - Path=/customer/**
              - id: banking-account-service
                uri: http://localhost:8083/api/v1/account
                predicates:
                  - Path=/account/**
              - id: banking-credit-service
                uri: http://localhost:8084/api/v1/credit
                predicates:
                  - Path=/credit/**
              - id: banking-card-service
                uri: http://localhost:8085/api/v1/card
                predicates:
                  - Path=/card/**
              - id: banking-deposit-service
                uri: http://localhost:8086/api/v1/deposit
                predicates:
                  - Path=/deposit/**
              - id: banking-witdrawal-service
                uri: http://localhost:8087/api/v1/witdrawal
                predicates:
                  - Path=/witdrawal/**
              - id: banking-transaction-service
                uri: http://localhost:8088/api/v1/transaction
                predicates:
                  - Path=/transaction/**
              - id: banking-payment-service
                uri: http://localhost:8089/api/v1/payment
                predicates:
                  - Path=/payment/**