server: 
  port: ${PORT:${SERVER_PORT:0}}
spring:
  data:
    mongodb:
        uri: mongodb+srv://jespinoza:jest444@jespinoza.is5j4.mongodb.net/customer_data
logging:
  file:
    name: log/CustomerService.log
  pattern:
    console: "%d [%thread] %-5level %-60logger{40} : %msg%n"
  logback:
    rollingpolicy:
      max-file-size: 1MB
      file-name-pattern: log/CustomerService-%d{yyyy-MM-dd}.%i.log
      total-size-cap: 11MB
      clean-history-on-start: true
      max-history: 10    
eureka:
  instance:
    prefer-ip-addres: true
  client: 
    service-url: 
      defaultZone: http://localhost:8091/eureka/
    instance:
        instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
management:
    endpoints:
        web:
          exposure:
            include: "*"
resilience4j.circuitbreaker:
    configs:
        default:
            registerHealthIndicator: true
    instances:
        accountCB:
            baseConfig: default
            failureRateThreshold: 50
            minimumNumberOfCalls: 10
            slidingWindowType: TIME_BASED
            slidingWindowSize: 10
            waitDurationInOpenState: 20s
            permittedNumberOfCallsInHalfOpenState: 3
        creditCB:
            baseConfig: default
            failureRateThreshold: 50
            minimumNumberOfCalls: 10
            slidingWindowType: TIME_BASED
            slidingWindowSize: 10
            waitDurationInOpenState: 20s
            permittedNumberOfCallsInHalfOpenState: 3
        cardCB:
            baseConfig: default
            failureRateThreshold: 50
            minimumNumberOfCalls: 10
            slidingWindowType: TIME_BASED
            slidingWindowSize: 10
            waitDurationInOpenState: 20s
            permittedNumberOfCallsInHalfOpenState: 3
        allCB:
            baseConfig: default
            failureRateThreshold: 50
            minimumNumberOfCalls: 10
            slidingWindowType: TIME_BASED
            slidingWindowSize: 10
            waitDurationInOpenState: 20s
            permittedNumberOfCallsInHalfOpenState: 3